# Generated by Django 5.2.10 on 2026-02-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='semester',
            new_name='kurs_davomiligi',
        ),
    ]
