# Generated by Django 5.2.10 on 2026-02-23 09:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Noyob talaba identifikatori', max_length=20, unique=True, verbose_name='Talaba ID')),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otasining ismi')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(help_text='Format: +998901234567', max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+?998\\d{9}$')], verbose_name='Telefon raqami')),
                ('alternative_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name="Qo'shimcha telefon")),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('date_of_birth', models.DateField(verbose_name="Tug'ilgan sana")),
                ('age', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Yosh')),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1, verbose_name='Jins')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Qon guruhi')),
                ('nationality', models.CharField(default="O'zbekiston", max_length=100, verbose_name='Millati')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Shahar')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyat')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pochta indeksi')),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ota-ona/Vasiy ismi')),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ota-ona telefoni')),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Ota-ona emaili')),
                ('guardian_relationship', models.CharField(blank=True, help_text='Masalan: ota, ona, aka, opa', max_length=50, null=True, verbose_name='Qarindoshlik darajasi')),
                ('previous_school', models.CharField(blank=True, max_length=200, null=True, verbose_name="Oldingi o'quv maskani")),
                ('education_level', models.CharField(blank=True, help_text="Masalan: O'rta maktab, Kollej, Universitet", max_length=100, null=True, verbose_name="Ta'lim darajasi")),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faol emas'), ('graduated', 'Bitirgan'), ('suspended', "To'xtatilgan"), ('dropped', 'Tashlab ketgan')], db_index=True, default='active', max_length=20, verbose_name='Holat')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name="Ro'yxatdan o'tgan sana")),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='Bitirgan sana')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Chegirma foizi')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='students/profiles/%Y/%m/', verbose_name='Profil rasmi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumotlar")),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Favqulodda vaziyat uchun aloqa')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Favqulodda aloqa telefoni')),
                ('medical_conditions', models.TextField(blank=True, help_text='Allergiya, kasalliklar va boshqalar', null=True, verbose_name="Tibbiy ma'lumotlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('courses', models.ManyToManyField(blank=True, related_name='students', through='enrollments.Enrollment', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan yaratilgan')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Pasport'), ('birth_certificate', "Tug'ilganlik haqida guvohnoma"), ('photo', 'Fotosurat'), ('certificate', 'Sertifikat'), ('contract', 'Shartnoma'), ('other', 'Boshqa')], max_length=50, verbose_name='Hujjat turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('file', models.FileField(upload_to='students/documents/%Y/%m/', verbose_name='Fayl')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student', verbose_name='Talaba')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_student_documents', to=settings.AUTH_USER_MODEL, verbose_name='Kim yukladi')),
            ],
            options={
                'verbose_name': 'Talaba hujjati',
                'verbose_name_plural': 'Talaba hujjatlari',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='students_st_student_e7126a_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='students_st_email_e271bc_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'last_name'], name='students_st_first_n_e9466d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_st_status_5e2210_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['city'], name='students_st_city_670107_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['enrollment_date'], name='students_st_enrollm_8263f3_idx'),
        ),
    ]
