# Generated by Django 5.2.10 on 2026-01-31 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='semester',
            new_name='kurs_davomiligi',
        ),
    ]
