# Generated by Django 5.2.10 on 2026-01-31 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_semester_course_kurs_davomiligi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credits',
            new_name='oylik_tolov',
        ),
    ]
