# Generated by Django 5.2.10 on 2026-02-01 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_credits_course_oylik_tolov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='oylik_tolov',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
